# @format

version: "3.8"

services:
  checkday:
    build: .
    image: 467465390813.dkr.ecr.us-east-1.amazonaws.com/checkday:latest
    ports:
      - "5969:5969"
    environment:
      - AWS_ACCESS_KEY_ID=${ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${SECRET_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - DATABASE_HOST=database
    depends_on:
      database:
        condition: service_healthy
    command: ["npm", "run", "start"]

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
