# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkday-deployment
  labels:
    app: checkday
spec:
  replicas: 4
  selector:
    matchLabels:
      app: checkday
  template:
    metadata:
      labels:
        app: checkday
    spec:
      containers:
        - name: checkday-container
          image: saitejsunkara/checkday:checkday
      imagePullSecrets:
        - name: checkday-docker-hub-secret
