# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkday-deployment
  labels:
    app: checkday
spec:
  replicas: 4
  selector:
    matchLabels:
      app: checkday
  template:
    metadata:
      labels:
        app: checkday
    spec:
      containers:
        - name: checkday-container
          image: 467465390813.dkr.ecr.us-east-1.amazonaws.com/checkday:checkday-image
          ports:
            - containerPort: 5969
      imagePullSecrets:
        - name: checkday-ecr-secret
