# @format

name: Continuous Integration
"on":
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DATABASE: "${{ secrets.DATABASE_NAME }}"
      USER: "${{ secrets.DATABASE_USERNAME }}"
      PASS: "${{ secrets.DATABASE_PASSWORD }}"
      HOST: "${{ secrets.DATABASE_HOST }}"
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - name: "Using, Node, Express, and Sequelize"
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"
          cache: npm
      - run: sudo systemctl start mysql
      - run: systemctl status mysql
