# @format

name: Build Packer App and AMI
"on":
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  packer-build:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_DIALECT: ${{ secrets.DATABASE_DIALECT }}
      APPLICATION_PORT: ${{ secrets.APPLICATION_PORT }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      SALT: ${{ secrets.SALT }}
      AES_KEY: ${{ secrets.AES_KEY }}
      INITIALIZATION_VECTOR: ${{ secrets.INITIALIZATION_VECTOR }}
      USER_COOKIE_AGE: ${{ secrets.USER_COOKIE_AGE }}
      IS_PRODUCTION: ${{ secrets.IS_PRODUCTION }}
      CRYPTO_ALGORITHM: ${{ secrets.CRYPTO_ALGORITHM }}
      CRYPTO_KEY: ${{ secrets.CRYPTO_KEY }}
      CRYPTO_IV_LENGTH: ${{ secrets.CRYPTO_IV_LENGTH }}
      SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - run: npm i
      - name: "Using, Node, Express, and Sequelize"
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"
          cache: npm
      - name: Install Packer
        run: >
          curl -SL
          https://releases.hashicorp.com/packer/1.4.2/packer_1.4.2_linux_amd64.zip
          -o packer_1.4.2_linux_amd64.zip

          unzip -o packer_1.4.2_linux_amd64.zip -d /tmp

          sudo mv /tmp/packer /usr/bin/packer

          packer --version
      - name: Create server.zip
        run: |
          zip -r server.zip .
      - name: Initialize Packer Configuration and Format packer file
        run: |
          packer init packer/checkday.pkr.hcl
          packer fmt packer/checkday.pkr.hcl
      - name: Validate Packer Configuration
        run: |
          packer validate packer/checkday.pkr.hcl
      - name: Build Amazon Machine Image
        run: |
          packer build packer/checkday.pkr.hcl
