# @format

name: Build Packer App and AMI
"on":
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  packer-build:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - run: npm i
      - name: "Using, Node, Express, and Sequelize"
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"
          cache: npm
      - name: Install Packer
        run: >
          curl -SL
          https://releases.hashicorp.com/packer/1.4.2/packer_1.4.2_linux_amd64.zip
          -o packer_1.4.2_linux_amd64.zip

          unzip -o packer_1.4.2_linux_amd64.zip -d /tmp

          sudo mv /tmp/packer /usr/bin/packer

          packer --version
      - name: Create server.zip
        run: |
          zip -r webapp.zip .
      - name: Build Amazon Machine Image
        run: |
          packer build packer/checkday.pkr.hcl
